name: kaspium_wallet
description: The Ultimate Self-Custodial Wallet for the Kaspa Network.
publish_to: "none"

version: 0.2.0+3

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_secure_storage: 8.0.0
  shared_preferences: 2.1.0
  package_info_plus: 3.0.3
  device_info_plus: 8.2.0
  json_annotation: 4.8.0
  intl: 0.17.0
  decimal: 2.3.2
  logger: 1.1.0
  hive_flutter: 1.1.0
  path_provider: 2.0.14
  local_auth: 2.1.6
  qr_flutter: 4.0.0
  qr_code_scanner: 1.0.1
  share_plus: 6.3.1
  file_picker: 5.2.7
  #uni_links: 0.5.1
  http: 0.13.5
  flutter_vibrate: 1.3.0
  flutter_slidable: 3.0.0
  validators: 3.0.0
  auto_size_text: 3.0.0
  url_launcher: 6.1.10
  flutter_riverpod: 2.3.4
  hooks_riverpod: 2.3.4
  flutter_hooks: 0.18.6
  freezed_annotation: 2.2.0
  fast_immutable_collections: 9.0.0
  cupertino_icons: 1.0.5
  oktoast: 3.3.1
  automatic_animated_list: 1.1.0
  lazy_load_scrollview: 1.3.0
  image_picker: 0.8.7+1
  barcode_finder: 0.0.5
  flutter_displaymode: 0.5.0
  push: 0.1.3
  crypton: 2.1.0
  cross_file: 0.3.3+4
  protobuf: 2.1.0
  grpc: 3.1.0
  coinslib: 3.1.7
  collection: 1.17.0
  fixnum: 1.0.1
  pointycastle: 3.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.3
  json_serializable: 6.6.1
  flutter_lints: 2.0.1
  freezed: 2.3.2
  flutter_launcher_icons: 0.13.1

# Flutter launcher icons
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/icon/icon_bg.png"
  image_path_ios: "assets/icon/icon_ios.png"
  adaptive_icon_background: "#232323"
  adaptive_icon_foreground: "assets/icon/icon_bg.png"

# The following section is specific to Flutter.
flutter:
  generate: true
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 600
        - asset: fonts/NunitoSans-ExtraLight.ttf
          weight: 100
        - asset: fonts/NunitoSans-Light.ttf
          weight: 200
        - asset: fonts/NunitoSans-SemiBold.ttf
          weight: 700
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 800
        - asset: fonts/NunitoSans-ExtraBold.ttf
          weight: 900
    - family: OverpassMono
      fonts:
        - asset: fonts/OverpassMono-Regular.ttf
          weight: 600
        - asset: fonts/OverpassMono-Light.ttf
          weight: 100
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
          weight: 500
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: fonts/Comfortaa-Light.ttf
          weight: 300
  assets:
    - assets/

  uses-material-design: true

scripts:
  codegen: flutter pub run build_runner build --delete-conflicting-outputs
